### PR TITLE
Pull Request for #1: Sped up R code x10-20

### PR DESCRIPTION
**Pull request by mcaceresb**
Done:

- 'return_matrix_list' is deprecated
- 'create_Atheta_list_*' and 'create_A0_list_*' use data.table and matrices instead of looping over lists; this is an order of magnitude faster.
- Adds data.table as a dependency; data.table is used in select places in the code to speed performance.
- eventTime loop is now internal; it no longer calls staggered recursively.
- While the simulation is still recursive, this call is much speedier.

Todo:

- Need to update documentation to reflect new data structures, as applicable.
- Need to clean up function descriptions and comments, as several have been deprecated.

@jonathandroth Can wait until I've cleaned up the comments/docs a bit (I saw some of the doxygen docs had examples which might need to be updated). LMK if I should do that here or have it in a follow-up.

Overall the code runs 10-20x faster, and is measurably faster than the Stata code.  I could've gotten it down another 2x at least but that would've required a substantial rewrite (the slowest part was the setup; as I mentioned I back-tracked and ended up leaving most of the list-based processing as it was after creating A_theta and A_0).

### CODE REVIEW

**Comment by jonathandroth** [comment]
Awesome - thanks, Mauricio! Why don't you update the documentation and then
I'll merge the PR.

**Comment by mcaceresb** [comment]
I'm copying my commends that noted what I did to speed up the function here, since I don't think it makes sense to keep them in the code comments. Feel free to ignore.

---

The generation of both Atheta and A0 relied on looping through various (g, t) combinations to generate a collection of vectors, and then aggregating them into a G by T matrix with various different weights. The internal function in each case is
                                                                                                                                                                                                                                                                                                                                                                                                              
- create_Atheta_list_for_ATE_tg
- create_A0_list_for_ATE_tg
                                                                                                                                                                                                                                                                                                                                                                                                              
In both cases, they used to return lists of length G with 1 x T vectors, and the requisite entry in each vector would be populated. Outer functions would then aggregate these lists with various weights, as mentioned. However, the results from these functions is more accurately represented by a G x 1 vector, since only a single column, the same one, of each 1 x T vector would be populated.
                                                                                                                                                                                                                                                                                                                                                                                                              
- For A_theta, it populates the (t_list == t) column
- For A_0, it populates the (t_list == (g-1)) column
                                                                                                                                                                                                                                                                                                                                                                                                              
In both cases, summing these base vectors or using them to populate G x T matrices, which are then aggregated, was the main speedup.

**Comment by mcaceresb** [comment]
@jonathandroth I updated the docs and debugged. Should be good to go. I also deprecated dplyr now everything's in `data.table`.

**Comment by jonathandroth** [comment]
Thanks, a lot!

One Q: it appears in line 157 of the README.md file that there was a slight
change in the pvalues for the FRT (0.63 vs 0.616). It could be that this is
Monte Carlo error, but I'd thought that by default staggered sets the seed
to 0 internally. Did I misremember that, or is there some (small) change in
how the FRT is working?

**Comment by mcaceresb** [comment]
@jonathandroth I added a line to sort the data by (i, t) so the starting order of the cohort vector was different. I've tried getting it back to exactly where it was but failed. Sadness. LMK if this is important. It remains internally consistent, however.

**Comment by jonathandroth** [comment]
I don't think that's a problem if it uses a slightly different sample of
permutations. I was just trying to figure out where the small discrepancies
were coming from. Wouldn't worry about exactly matching the previous results

**Pull request merged**
